### ISSUE TITLE
Files not downloading

### ISSUE THREAD

**Issue by branchard** [Mys7erio/aiotorrent#7]
Here is my code:
```py
from aiotorrent import Torrent
import urllib.request
import os

TEMP_DIR = "./.temp"
torrent_url = "https://archive.org/download/jvarchive_dump_dec._2024/jvarchive_dump_dec._2024_archive.torrent"

print(f"Downloading torrent file from {torrent_url} to {TEMP_DIR}…")
torrent_file_path, result = urllib.request.urlretrieve(torrent_url, os.path.join(TEMP_DIR, "jvarchive_dump_dec_2024_archive.torrent"))
print(f"Torrent file downloaded to {torrent_file_path}")

print(f"Starting torrent download…")
torrent = Torrent(torrent_file_path)
await torrent.init()
await torrent.download(torrent.files[0])
```

The file to be downloaded is created, but no data is written, it never exceeds 0 bytes.

I tested with qBittorrent, the file downloads correctly.

**Comment by Mys7erio** [comment]
Hi, I ran tried using the same torrent file with aiotorrent, and here's the logs:

```
python .\example.py .\utils\jvarchive_dump_dec._2024_archive.torrent
DEBUG:asyncio:Using selector: SelectSelector
****************************************************************
INFO:aiotorrent.aiotorrent:File: jvarchive_dump_dec._2024.zip (11634676422)
INFO:aiotorrent.aiotorrent:File: .____padding_file (322874)
INFO:aiotorrent.aiotorrent:File: jvarchive_dump_dec._2024_meta.sqlite (20480)
INFO:aiotorrent.aiotorrent:File: .____padding_file (4173824)
INFO:aiotorrent.aiotorrent:File: jvarchive_dump_dec._2024_meta.xml (939)
INFO:aiotorrent.aiotorrent:File: .____padding_file (4193365)
Started Execution at: 2024-12-06 16:57:10.160871
[jvarchive_dump_dec._2024.zip (11634676422), .____padding_file (322874), jvarchive_dump_dec._2024_meta.sqlite (20480), .____padding_file (4173824), jvarchive_dump_dec._2024_meta.xml (939), .____padding_file (4193365)]
DEBUG:aiotorrent.core.trackers: http object skipped...
DEBUG:aiotorrent.core.trackers: http object skipped...
INFO:aiotorrent.aiotorrent:Got 0 Peers for this torrent
INFO:aiotorrent.aiotorrent:0 peers active
INFO:aiotorrent.aiotorrent:0 trackers active
INFO:aiotorrent.aiotorrent:Using strategy DownloadStrategy.SEQUENTIAL to download file jvarchive_dump_dec._2024.zip (11634676422)
```

The following lines state that aiotorrent wasn't able to connect to any trackers, and hence couldn't connect to any peers either.
```
INFO:aiotorrent.aiotorrent:0 peers active
INFO:aiotorrent.aiotorrent:0 trackers active
```

Diving further, I looked at the trackers listed inside the torrent file:
`['http://bt1.archive.org:6969/announce', 'http://bt2.archive.org:6969/announce']`

and I can confirm that these are HTTP trackers, which are not supported (only UDP is supported) at the moment.

HTTP trackers have long been in the plans, but unfortunately I prioritised working on optimising the download speeds and download strategies, and haven't been able to add this feature.

I'll try working on this issue, however I can't provide a specific timeline of when it will be done. I hope you understand.

**Comment by Mys7erio** [comment]
I pushed an update which implements HTTP and HTTPS trackers and it works (successfully fetches peers from those peers). Altho it's in experimental stage right now, You can try downloading the torrent file again let me know.

> [!NOTE]
PS: The download still might be stuck as the download might be subject to peer availablility.

Modern torrent clients use DHTs to get more peers, so I'll definitely add it to the list of milestones for now, but I'll leave the implementation out for a later date.

I also will be closing the issue now. Feel free to re-open it if you deem necessary.

**Comment by Mys7erio** [comment]
.

**Comment by branchard** [comment]
Thank you for your responsiveness, but it still doesn't seem to work.
```
python .\example.py F:\.temp\jvarchive_dump_dec_2024_archive.torrent
****************************************************************
INFO:aiotorrent.aiotorrent:File: jvarchive_dump_dec._2024.zip (11634676422)
INFO:aiotorrent.aiotorrent:File: .____padding_file (322874)
INFO:aiotorrent.aiotorrent:File: jvarchive_dump_dec._2024_meta.sqlite (20480)
INFO:aiotorrent.aiotorrent:File: .____padding_file (4173824)
INFO:aiotorrent.aiotorrent:File: jvarchive_dump_dec._2024_meta.xml (939)
INFO:aiotorrent.aiotorrent:File: .____padding_file (4193365)
Started Execution at: 2024-12-19 01:29:18.475461
INFO:aiotorrent.aiotorrent:Got 1 Peers for this torrent
INFO:aiotorrent.aiotorrent:0 peers active
INFO:aiotorrent.aiotorrent:0 trackers active
INFO:aiotorrent.aiotorrent:Using strategy DownloadStrategy.SEQUENTIAL to download file jvarchive_dump_dec._2024.zip (11634676422)
```

Maybe I missed something?

**Comment by Mys7erio** [comment]
Torrents work like this:
 - Retrieve peers from trackers
 - Try and connect to those peers to see which ones are active
 - Start downloading pieces of the file from peers

In the logs you've pasted, it shows that it was able to retrive only 1 peer from both the trackers (happens with old torrents which don't have many seeders), and it tried connecting to this peer, but the connection failed, and so the download is stalled.

Torrent clients like qBittorrent use other protocols (DHT, PeX are the most effective ones imo) in addition to torrent trackers to circumnavigate around this issue, and get more peers for any particular torrent.

Seeing your case, I have planned the addition of DHT into aiotorrent but again, I can't quite be sure by when can I push this update
